<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Plots</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Plots_For_class_files/libs/clipboard/clipboard.min.js"></script>
<script src="Plots_For_class_files/libs/quarto-html/quarto.js"></script>
<script src="Plots_For_class_files/libs/quarto-html/popper.min.js"></script>
<script src="Plots_For_class_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Plots_For_class_files/libs/quarto-html/anchor.min.js"></script>
<link href="Plots_For_class_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Plots_For_class_files/libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Plots_For_class_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Plots_For_class_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Plots_For_class_files/libs/bootstrap/bootstrap-1bc8a17f135ab3d594c857e9f48e611b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Plots</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="load-libraries" class="level2">
<h2 class="anchored" data-anchor-id="load-libraries">Load Libraries</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(here)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggpubr)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="load-data" class="level2">
<h2 class="anchored" data-anchor-id="load-data">Load Data</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>Bites <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="fu">here</span>(<span class="st">"Data"</span>, <span class="st">"Bite_Rates.csv"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">everything</span>(), <span class="sc">~</span><span class="fu">replace</span>(., <span class="fu">is.na</span>(.), <span class="dv">0</span>))) <span class="sc">%&gt;%</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Total_Bites =</span> Coral_Bites <span class="sc">+</span> Rubble_Bites <span class="sc">+</span> Sand_Bites <span class="sc">+</span> Turf_Bites <span class="sc">+</span> Macro_Bites <span class="sc">+</span> CCA_Bites <span class="sc">+</span> Sponge_Bites) <span class="sc">%&gt;%</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Bites_per_min =</span> <span class="fu">case_when</span>(</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>    Species <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"A triostegus"</span>,  <span class="st">"C spilurus"</span>) <span class="sc">~</span> Total_Bites <span class="sc">/</span> <span class="dv">3</span>,</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>    Species <span class="sc">==</span> <span class="st">"Z cornutus"</span> <span class="sc">~</span> Total_Bites <span class="sc">/</span> <span class="dv">7</span>))</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="do">#######################################</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>Transects_raw<span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="fu">here</span>(<span class="st">"Data"</span>, <span class="st">"Transects.csv"</span>)) <span class="co"># read in transect data</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>substrate_availability<span class="ot">&lt;-</span> Transects_raw <span class="sc">%&gt;%</span> </span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Select only the columns we need (column 12 has location names, 13-19 have percentages)</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Use backticks ` ` because column names have spaces and % symbols</span></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="at">Location =</span> <span class="st">`</span><span class="at">...12</span><span class="st">`</span>, <span class="co"># Column 12 (unnamed, so R calls it ...12) has "Slope", "Flat", "Lagoon"</span></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>         <span class="at">Coral_Avail =</span> <span class="st">`</span><span class="at">% coral</span><span class="st">`</span>, <span class="co"># Rename to simpler names without spaces</span></span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>         <span class="at">Rubble_Avail =</span> <span class="st">`</span><span class="at">% rubble</span><span class="st">`</span>,</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>         <span class="at">Sand_Avail =</span> <span class="st">`</span><span class="at">% sand</span><span class="st">`</span>,</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>         <span class="at">Turf_Avail =</span> <span class="st">`</span><span class="at">% turf</span><span class="st">`</span>,</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>         <span class="at">Macro_Avail =</span> <span class="st">`</span><span class="at">% macro</span><span class="st">`</span>,</span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>         <span class="at">CCA_Avail =</span> <span class="st">`</span><span class="at">% CCA</span><span class="st">`</span>,</span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>         <span class="at">Sponge_Avail =</span> <span class="st">`</span><span class="at">% sponge</span><span class="st">`</span>) <span class="sc">%&gt;%</span></span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Location)) <span class="sc">%&gt;%</span> <span class="co"># Keep only rows where Location is not NA (removes all the empty rows)</span></span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Location =</span> <span class="fu">case_when</span>(Location <span class="sc">==</span> <span class="st">"Slope"</span> <span class="sc">~</span> <span class="st">"S"</span>, <span class="co"># Change location names to match the Bites data (S, F, L instead of Slope, Flat, Lagoon)</span></span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a>                              Location <span class="sc">==</span> <span class="st">"Flat"</span> <span class="sc">~</span> <span class="st">"F"</span>,</span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a>                              Location <span class="sc">==</span> <span class="st">"Lagoon"</span> <span class="sc">~</span> <span class="st">"L"</span>))</span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a><span class="co"># view(substrate_availability)</span></span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a><span class="do">#######################################</span></span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a>Time_Foraging<span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="fu">here</span>(<span class="st">"Data"</span>, <span class="st">"Time Foraging.csv"</span>)) </span>
<span id="cb2-31"><a href="#cb2-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-32"><a href="#cb2-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-33"><a href="#cb2-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-34"><a href="#cb2-34" aria-hidden="true" tabindex="-1"></a><span class="co"># These are for when all of the transect data is inputted so we can run a Strauss Selectivity Test</span></span>
<span id="cb2-35"><a href="#cb2-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-36"><a href="#cb2-36" aria-hidden="true" tabindex="-1"></a>Flats_Bites <span class="ot">&lt;-</span> Bites <span class="sc">%&gt;%</span></span>
<span id="cb2-37"><a href="#cb2-37" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Location <span class="sc">==</span> <span class="st">"F"</span>)</span>
<span id="cb2-38"><a href="#cb2-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-39"><a href="#cb2-39" aria-hidden="true" tabindex="-1"></a>Slope_Bites <span class="ot">&lt;-</span> Bites <span class="sc">%&gt;%</span></span>
<span id="cb2-40"><a href="#cb2-40" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Location <span class="sc">==</span> <span class="st">"S"</span>)</span>
<span id="cb2-41"><a href="#cb2-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-42"><a href="#cb2-42" aria-hidden="true" tabindex="-1"></a>Lagoon_Bites <span class="ot">&lt;-</span> Bites <span class="sc">%&gt;%</span></span>
<span id="cb2-43"><a href="#cb2-43" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Location <span class="sc">==</span> <span class="st">"L"</span>)</span>
<span id="cb2-44"><a href="#cb2-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-45"><a href="#cb2-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-46"><a href="#cb2-46" aria-hidden="true" tabindex="-1"></a><span class="fu">view</span>(Bites)</span>
<span id="cb2-47"><a href="#cb2-47" aria-hidden="true" tabindex="-1"></a><span class="fu">view</span>(Flats_Bites)</span>
<span id="cb2-48"><a href="#cb2-48" aria-hidden="true" tabindex="-1"></a><span class="fu">view</span>(Slope_Bites)</span>
<span id="cb2-49"><a href="#cb2-49" aria-hidden="true" tabindex="-1"></a><span class="fu">view</span>(Lagoon_Bites)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="lets-make-a-plot" class="level2">
<h2 class="anchored" data-anchor-id="lets-make-a-plot">Lets make a plot</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>LR1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> Bites, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Size, <span class="at">y =</span> Bites_per_min)) <span class="sc">+</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">TRUE</span>, <span class="at">color =</span> <span class="st">"cyan3"</span>, <span class="at">fill =</span> <span class="st">"aquamarine"</span>) <span class="sc">+</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>     <span class="fu">stat_regline_equation</span>(</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">label =</span> ..eq.label..),</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">label.x =</span> <span class="dv">14</span>, </span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">label.y =</span> <span class="dv">65</span> ) <span class="sc">+</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">stat_cor</span>(</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">label =</span> ..rr.label..),</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">label.x =</span> <span class="dv">14</span>,</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">label.y =</span> <span class="dv">60</span>) <span class="sc">+</span></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> Species)</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>LR2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> Bites, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Size, <span class="at">y =</span> Bites_per_min)) <span class="sc">+</span></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color =</span> Species)) <span class="sc">+</span></span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">TRUE</span>, <span class="at">color =</span> <span class="st">"cyan3"</span>, <span class="at">fill =</span> <span class="st">"aquamarine"</span>) <span class="sc">+</span></span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>     <span class="fu">stat_regline_equation</span>(</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">label =</span> ..eq.label..),</span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">label.x =</span> <span class="dv">14</span>, </span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">label.y =</span> <span class="dv">65</span> ) <span class="sc">+</span></span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a>    <span class="fu">stat_cor</span>(</span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">label =</span> ..rr.label..),</span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">label.x =</span> <span class="dv">14</span>,</span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">label.y =</span> <span class="dv">60</span>)</span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a>LR1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Plots_For_class_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>LR2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Plots_For_class_files/figure-html/unnamed-chunk-3-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="strauss-selectivity-index" class="level1">
<h1>Strauss Selectivity Index</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate Bite Proportions (What the fish are eating)</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Strauss formula: L = r - p </span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="co"># r = proportion of bites on each substrate (what they're eating)</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="co"># p = proportion available (what's there) — we have this in substrate_availability</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate r</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>bite_proportions<span class="ot">&lt;-</span> Bites <span class="sc">%&gt;%</span> </span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Species, Age_Class, Location) <span class="sc">%&gt;%</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>( <span class="co"># sum up all bites for each substrate type within each group</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">Coral_Bites =</span> <span class="fu">sum</span>(Coral_Bites),</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">Rubble_Bites =</span> <span class="fu">sum</span>(Rubble_Bites),</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">Sand_Bites =</span> <span class="fu">sum</span>(Sand_Bites),</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">Turf_Bites =</span> <span class="fu">sum</span>(Turf_Bites),</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">Macro_Bites =</span> <span class="fu">sum</span>(Macro_Bites),</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">CCA_Bites =</span> <span class="fu">sum</span>(CCA_Bites),</span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">Sponge_Bites =</span> <span class="fu">sum</span>(Sponge_Bites),</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">Total_Bites =</span> <span class="fu">sum</span>(Total_Bites), <span class="co"># calculate total bites acros all substrates </span></span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">n_observations =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span> <span class="co"># count how many fish observations are in each group </span></span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>( <span class="co"># calculate proportions = bites on substrate / total bites </span></span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">Coral_Prop =</span> (Coral_Bites <span class="sc">/</span> Total_Bites) <span class="sc">*</span> <span class="dv">100</span>, <span class="co"># multiply by 100 to get % to match substrate_availability</span></span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">Rubble_Prop =</span> (Rubble_Bites <span class="sc">/</span> Total_Bites) <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">Sand_Prop =</span> (Sand_Bites <span class="sc">/</span> Total_Bites) <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">Turf_Prop =</span> (Turf_Bites <span class="sc">/</span> Total_Bites) <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">Macro_Prop =</span> (Macro_Bites <span class="sc">/</span> Total_Bites) <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">CCA_Prop =</span> (CCA_Bites <span class="sc">/</span> Total_Bites) <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a>    <span class="at">Sponge_Prop =</span> (Sponge_Bites <span class="sc">/</span> Total_Bites) <span class="sc">*</span> <span class="dv">100</span>)</span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a><span class="co">#view(bite_proportions)</span></span>
<span id="cb5-29"><a href="#cb5-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-30"><a href="#cb5-30" aria-hidden="true" tabindex="-1"></a><span class="co"># Join Bite Proportions with substrate availability</span></span>
<span id="cb5-31"><a href="#cb5-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-32"><a href="#cb5-32" aria-hidden="true" tabindex="-1"></a>strauss_data<span class="ot">&lt;-</span> bite_proportions <span class="sc">%&gt;%</span></span>
<span id="cb5-33"><a href="#cb5-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(substrate_availability, <span class="at">by =</span> <span class="st">"Location"</span>) <span class="co"># connect two tables by "location" column </span></span>
<span id="cb5-34"><a href="#cb5-34" aria-hidden="true" tabindex="-1"></a><span class="co"># keep all rows from bite_proportions and add matching columns from substrate_availability</span></span>
<span id="cb5-35"><a href="#cb5-35" aria-hidden="true" tabindex="-1"></a><span class="co">#view(strauss_data)</span></span>
<span id="cb5-36"><a href="#cb5-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-37"><a href="#cb5-37" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate L (strauss slectivity index) for each substrate</span></span>
<span id="cb5-38"><a href="#cb5-38" aria-hidden="true" tabindex="-1"></a><span class="co"># L = r - p</span></span>
<span id="cb5-39"><a href="#cb5-39" aria-hidden="true" tabindex="-1"></a><span class="co"># L = proportion of bites (what they ate) - proportion available (what was there)</span></span>
<span id="cb5-40"><a href="#cb5-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-41"><a href="#cb5-41" aria-hidden="true" tabindex="-1"></a>strauss_results<span class="ot">&lt;-</span> strauss_data <span class="sc">%&gt;%</span></span>
<span id="cb5-42"><a href="#cb5-42" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Coral_L =</span> Coral_Prop <span class="sc">-</span> Coral_Avail,</span>
<span id="cb5-43"><a href="#cb5-43" aria-hidden="true" tabindex="-1"></a>         <span class="at">Rubble_L =</span> Rubble_Prop <span class="sc">-</span> Rubble_Avail,</span>
<span id="cb5-44"><a href="#cb5-44" aria-hidden="true" tabindex="-1"></a>         <span class="at">Sand_L =</span> Sand_Prop <span class="sc">-</span> Sand_Avail,</span>
<span id="cb5-45"><a href="#cb5-45" aria-hidden="true" tabindex="-1"></a>         <span class="at">Turf_L =</span> Turf_Prop <span class="sc">-</span> Turf_Avail,</span>
<span id="cb5-46"><a href="#cb5-46" aria-hidden="true" tabindex="-1"></a>         <span class="at">Macro_L =</span> Macro_Prop <span class="sc">-</span> Macro_Avail,</span>
<span id="cb5-47"><a href="#cb5-47" aria-hidden="true" tabindex="-1"></a>         <span class="at">CCA_L =</span> CCA_Prop <span class="sc">-</span> CCA_Avail,</span>
<span id="cb5-48"><a href="#cb5-48" aria-hidden="true" tabindex="-1"></a>         <span class="at">Sponge_L =</span> Sponge_Prop <span class="sc">-</span> Sponge_Avail)</span>
<span id="cb5-49"><a href="#cb5-49" aria-hidden="true" tabindex="-1"></a>strauss_results <span class="sc">%&gt;%</span></span>
<span id="cb5-50"><a href="#cb5-50" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Species, Age_Class, Location, <span class="co"># look at just selectivity results (L values)</span></span>
<span id="cb5-51"><a href="#cb5-51" aria-hidden="true" tabindex="-1"></a>         Coral_L, Rubble_L, Sand_L, Turf_L, Macro_L, CCA_L, Sponge_L)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 13 × 10
# Groups:   Species, Age_Class [6]
   Species     Age_Class Location Coral_L Rubble_L Sand_L Turf_L Macro_L   CCA_L
   &lt;chr&gt;       &lt;chr&gt;     &lt;chr&gt;      &lt;dbl&gt;    &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
 1 A triosteg… Adult     F          -36.4    69.1   -40.6   8.76   0     -0.833 
 2 A triosteg… Adult     L          -11.8    10.7   -40.4  37.2    6.87  -2.5   
 3 A triosteg… Juvenile  F          -36.7   -12.4   -40.8  90.4    0     -0.572 
 4 A triosteg… Juvenile  L          -12.3    11.8   -39.7  44.5   -1.84  -2.5   
 5 C spilurus  Adult     F          -36.7    29.3    17.4  -9.17   0     -0.833 
 6 C spilurus  Adult     L          -10.5     1.57  -27.9  41.4   -2.13  -2.5   
 7 C spilurus  Adult     S          -26.1    66.9   -12.5 -15     -4.17  -5.83  
 8 C spilurus  Juvenile  F          -33.4   -10.8   -40.8  85.4    0.456 -0.833 
 9 C spilurus  Juvenile  L          -12.1    11.6   -34.0  39.2   -2.5   -2.22  
10 Z cornutus  Adult     L          -12.5   -14.2   -40.8  72.5   -2.5   -2.5   
11 Z cornutus  Adult     S          -35.8    -1.67  -13.3   4.44  -4.17  -1.67  
12 Z cornutus  Juvenile  L          -11.7    46.5   -39.6  -6.31  -2.5   -0.0309
13 Z cornutus  Juvenile  S          -44.2    -7.62  -13.3  49.5   -4.17  -5.83  
# ℹ 1 more variable: Sponge_L &lt;dbl&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># For reference: -value means fish avoid, +value means fish prefer</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Interpreting Results Positive = preference, Negative = avoidance</p>
<p><strong>A triostegus</strong>:</p>
<p>Loves turf algae. Juveniles in the Flats have a selectivity of +90.4! Avoids coral and sand (all negative values) Adults also like rubble in Flats (+69.1)</p>
<p><strong>C spilurus</strong>:</p>
<p>Juveniles love turf (+85.4 in Flats) Adults are more variable — prefer rubble on Slope (+66.9), turf in Lagoon (+41.4), and even sand in Flats (+17.4) Adults on Slope strongly avoid turf (-15.0)</p>
<p><strong>Z cornutus</strong>:</p>
<p>Adults on Slope love sponge! (+52.2) Juveniles also eat sponge more than expected (+25.6 on Slope, +13.6 in Lagoon) Juveniles in Lagoon prefer rubble (+46.5) All groups avoid coral (all negative)</p>
</section>
<section id="strauss-plot" class="level1">
<h1>Strauss Plot</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># reshape data into long format for ggplot</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>strauss_long<span class="ot">&lt;-</span> strauss_results<span class="sc">%&gt;%</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Species, Age_Class, Location,<span class="co"># select columns for plot</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>         Coral_L, Rubble_L, Sand_L, Turf_L, Macro_L, CCA_L, Sponge_L) <span class="sc">%&gt;%</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> Coral_L<span class="sc">:</span>Sponge_L,<span class="co"># columns to resshape</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>               <span class="at">names_to =</span> <span class="st">"Substrate"</span>, <span class="co"># new column name for substrate types</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>               <span class="at">values_to =</span> <span class="st">"Selectivity"</span>) <span class="sc">%&gt;%</span> <span class="co"># new column name for L values </span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Substrate =</span> <span class="fu">str_replace</span>(Substrate, <span class="st">"_L"</span>, <span class="st">""</span>)) <span class="sc">%&gt;%</span> <span class="co"># clean substrate names ( remove "_L" from end of name)</span></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Location =</span> <span class="fu">case_when</span>( <span class="co"># change location codes to full names for plot </span></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>    Location <span class="sc">==</span> <span class="st">"F"</span> <span class="sc">~</span> <span class="st">"Flats"</span>,</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>    Location <span class="sc">==</span> <span class="st">"L"</span> <span class="sc">~</span> <span class="st">"Lagoon"</span>,</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>    Location <span class="sc">==</span> <span class="st">"S"</span> <span class="sc">~</span> <span class="st">"Slope"</span>))</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot</span></span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>strauss_plot<span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> strauss_long, <span class="co"># plot data </span></span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>                      <span class="fu">aes</span>(<span class="at">x =</span> Substrate,</span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>                          <span class="at">y =</span> Selectivity,</span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a>                          <span class="at">fill =</span> Substrate)) <span class="sc">+</span></span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>()<span class="sc">+</span> <span class="co"># bar plot</span></span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">color =</span> <span class="st">"black"</span>)<span class="sc">+</span> <span class="co"># add horizontal reference line at 0 </span></span>
<span id="cb8-22"><a href="#cb8-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(Species <span class="sc">+</span> Age_Class <span class="sc">~</span> Location)<span class="sc">+</span> <span class="co"># create separate panels for each species and age class </span></span>
<span id="cb8-23"><a href="#cb8-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_d</span>(<span class="at">option =</span> <span class="st">"magma"</span>)<span class="sc">+</span> <span class="co"># color blind friendly </span></span>
<span id="cb8-24"><a href="#cb8-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>))<span class="sc">+</span> <span class="co"># rotate axis labels</span></span>
<span id="cb8-25"><a href="#cb8-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Strauss Selectivity Index by Species, Age Class, and Location"</span>,</span>
<span id="cb8-26"><a href="#cb8-26" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Positive values = preference, Negative values = avoidance"</span>,</span>
<span id="cb8-27"><a href="#cb8-27" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Substrate Type"</span>,</span>
<span id="cb8-28"><a href="#cb8-28" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Selectivity Index (L)"</span>,</span>
<span id="cb8-29"><a href="#cb8-29" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">"Substrate"</span>)</span>
<span id="cb8-30"><a href="#cb8-30" aria-hidden="true" tabindex="-1"></a>strauss_plot</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Plots_For_class_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="fu">here</span>(<span class="st">"output"</span>, <span class="st">"strauss_plot.png"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="conspecific-substrate-preference-juv-vs-adult" class="level1">
<h1>Conspecific Substrate Preference (Juv vs adult)</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># comparing the substrate preference for juveniles and adults for the same species to answer hypothesis 2 better, only using preferences which came out to 3 per species</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>bite_proportions <span class="ot">&lt;-</span> Bites <span class="sc">%&gt;%</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">Coral_Prop   =</span> (Coral_Bites   <span class="sc">/</span> Total_Bites) <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">Rubble_Prop  =</span> (Rubble_Bites  <span class="sc">/</span> Total_Bites) <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">Sand_Prop    =</span> (Sand_Bites    <span class="sc">/</span> Total_Bites) <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">Turf_Prop    =</span> (Turf_Bites    <span class="sc">/</span> Total_Bites) <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">Macro_Prop   =</span> (Macro_Bites   <span class="sc">/</span> Total_Bites) <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">CCA_Prop     =</span> (CCA_Bites     <span class="sc">/</span> Total_Bites) <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">Sponge_Prop  =</span> (Sponge_Bites  <span class="sc">/</span> Total_Bites) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Join with substrate availability by location</span></span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>strauss_data <span class="ot">&lt;-</span> bite_proportions <span class="sc">%&gt;%</span></span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(substrate_availability, <span class="at">by =</span> <span class="st">"Location"</span>)</span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate Strauss selectivity index (L = r - p) for each individual</span></span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a>strauss_results_indv <span class="ot">&lt;-</span> strauss_data <span class="sc">%&gt;%</span></span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">Coral_L   =</span> Coral_Prop   <span class="sc">-</span> Coral_Avail,</span>
<span id="cb10-22"><a href="#cb10-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">Rubble_L  =</span> Rubble_Prop  <span class="sc">-</span> Rubble_Avail,</span>
<span id="cb10-23"><a href="#cb10-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">Sand_L    =</span> Sand_Prop    <span class="sc">-</span> Sand_Avail,</span>
<span id="cb10-24"><a href="#cb10-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">Turf_L    =</span> Turf_Prop    <span class="sc">-</span> Turf_Avail,</span>
<span id="cb10-25"><a href="#cb10-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">Macro_L   =</span> Macro_Prop   <span class="sc">-</span> Macro_Avail,</span>
<span id="cb10-26"><a href="#cb10-26" aria-hidden="true" tabindex="-1"></a>    <span class="at">CCA_L     =</span> CCA_Prop     <span class="sc">-</span> CCA_Avail,</span>
<span id="cb10-27"><a href="#cb10-27" aria-hidden="true" tabindex="-1"></a>    <span class="at">Sponge_L  =</span> Sponge_Prop  <span class="sc">-</span> Sponge_Avail</span>
<span id="cb10-28"><a href="#cb10-28" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb10-29"><a href="#cb10-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-30"><a href="#cb10-30" aria-hidden="true" tabindex="-1"></a>strauss_results_indv <span class="sc">%&gt;%</span></span>
<span id="cb10-31"><a href="#cb10-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Species, Age_Class, Location,</span>
<span id="cb10-32"><a href="#cb10-32" aria-hidden="true" tabindex="-1"></a>         Coral_L, Rubble_L, Sand_L, Turf_L, Macro_L, CCA_L, Sponge_L)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 120 × 10
   Species    Age_Class Location Coral_L Rubble_L Sand_L Turf_L Macro_L  CCA_L
   &lt;chr&gt;      &lt;chr&gt;     &lt;chr&gt;      &lt;dbl&gt;    &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;
 1 Z cornutus Juvenile  L           16.1     40.6  -40.8  -10.8   -2.5   -2.5 
 2 Z cornutus Juvenile  L          -12.5     46.4  -40.8   11.9   -2.5   -2.5 
 3 Z cornutus Juvenile  L          -12.5     35.8  -40.8   22.5   -2.5   -2.5 
 4 Z cornutus Juvenile  S          -44.2    -14.2  -13.3   85     -4.17  -5.83
 5 Z cornutus Juvenile  S          -44.2    -14.2  -13.3   85     -4.17  -5.83
 6 Z cornutus Juvenile  L          -12.5     69.2  -40.8  -10.8   -2.5   -2.5 
 7 Z cornutus Juvenile  L          -12.5     69.2  -40.8  -10.8   -2.5   -2.5 
 8 Z cornutus Juvenile  L          -12.5     16.8  -40.8  -10.8   -2.5   -2.5 
 9 Z cornutus Juvenile  L          NaN      NaN    NaN    NaN    NaN    NaN   
10 Z cornutus Juvenile  L          -12.5    -30.8  -40.8  -10.8   -2.5   97.5 
# ℹ 110 more rows
# ℹ 1 more variable: Sponge_L &lt;dbl&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>strauss_atrio <span class="ot">&lt;-</span> strauss_results_indv <span class="sc">%&gt;%</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Species <span class="sc">==</span> <span class="st">"A triostegus"</span>)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>strauss_cspil <span class="ot">&lt;-</span> strauss_results_indv <span class="sc">%&gt;%</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Species <span class="sc">==</span> <span class="st">"C spilurus"</span>)</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>strauss_zcorn <span class="ot">&lt;-</span> strauss_results_indv <span class="sc">%&gt;%</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Species <span class="sc">==</span> <span class="st">"Z cornutus"</span>)</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a><span class="fu">view</span>(strauss_atrio)</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(Rubble_L <span class="sc">~</span> Age_Class, <span class="at">data =</span> strauss_atrio)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  Rubble_L by Age_Class
t = 1.7443, df = 36.368, p-value = 0.08955
alternative hypothesis: true difference in means between group Adult and group Juvenile is not equal to 0
95 percent confidence interval:
 -4.252851 56.672125
sample estimates:
   mean in group Adult mean in group Juvenile 
              38.29803               12.08839 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(Turf_L <span class="sc">~</span> Age_Class, <span class="at">data =</span> strauss_atrio)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  Turf_L by Age_Class
t = -2.0783, df = 36.279, p-value = 0.04481
alternative hypothesis: true difference in means between group Adult and group Juvenile is not equal to 0
95 percent confidence interval:
 -60.3491462  -0.7462794
sample estimates:
   mean in group Adult mean in group Juvenile 
              18.92768               49.47540 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(Macro_L <span class="sc">~</span> Age_Class, <span class="at">data =</span> strauss_atrio)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  Macro_L by Age_Class
t = 1.427, df = 18.38, p-value = 0.1704
alternative hypothesis: true difference in means between group Adult and group Juvenile is not equal to 0
95 percent confidence interval:
 -4.07652 21.41872
sample estimates:
   mean in group Adult mean in group Juvenile 
              7.399547              -1.271552 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(Rubble_L <span class="sc">~</span> Age_Class, <span class="at">data =</span> strauss_cspil)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  Rubble_L by Age_Class
t = 1.6118, df = 35.51, p-value = 0.1159
alternative hypothesis: true difference in means between group Adult and group Juvenile is not equal to 0
95 percent confidence interval:
 -5.008795 43.699070
sample estimates:
   mean in group Adult mean in group Juvenile 
             21.902080               2.556943 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(Sand_L <span class="sc">~</span> Age_Class, <span class="at">data =</span> strauss_cspil)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  Sand_L by Age_Class
t = 2.9436, df = 22.197, p-value = 0.007468
alternative hypothesis: true difference in means between group Adult and group Juvenile is not equal to 0
95 percent confidence interval:
  5.306716 30.570622
sample estimates:
   mean in group Adult mean in group Juvenile 
             -19.71321              -37.65188 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(Turf_L <span class="sc">~</span> Age_Class, <span class="at">data =</span> strauss_cspil)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  Turf_L by Age_Class
t = -3.0699, df = 37.95, p-value = 0.003943
alternative hypothesis: true difference in means between group Adult and group Juvenile is not equal to 0
95 percent confidence interval:
 -69.28808 -14.21894
sample estimates:
   mean in group Adult mean in group Juvenile 
              20.52905               62.28256 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(Rubble_L <span class="sc">~</span> Age_Class, <span class="at">data =</span> strauss_zcorn)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  Rubble_L by Age_Class
t = -1.5311, df = 23.198, p-value = 0.1393
alternative hypothesis: true difference in means between group Adult and group Juvenile is not equal to 0
95 percent confidence interval:
 -51.276325   7.644518
sample estimates:
   mean in group Adult mean in group Juvenile 
                2.5000                24.3159 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(Turf_L <span class="sc">~</span> Age_Class, <span class="at">data =</span> strauss_zcorn)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  Turf_L by Age_Class
t = -0.0037009, df = 24.97, p-value = 0.9971
alternative hypothesis: true difference in means between group Adult and group Juvenile is not equal to 0
95 percent confidence interval:
 -28.29347  28.19197
sample estimates:
   mean in group Adult mean in group Juvenile 
              19.08654               19.13729 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(Sponge_L <span class="sc">~</span> Age_Class, <span class="at">data =</span> strauss_zcorn)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  Sponge_L by Age_Class
t = 1.3999, df = 16.393, p-value = 0.1802
alternative hypothesis: true difference in means between group Adult and group Juvenile is not equal to 0
95 percent confidence interval:
 -8.177929 40.160549
sample estimates:
   mean in group Adult mean in group Juvenile 
              27.72894               11.73763 </code></pre>
</div>
</div>
</section>
<section id="a-trio-conspecific-substrate-differences-adult-vs-juvenile" class="level1">
<h1>A trio conspecific substrate differences (adult vs juvenile)</h1>
<table class="caption-top table">
<colgroup>
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 7%">
<col style="width: 9%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 11%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>Substrate</th>
<th>t statistic</th>
<th>df</th>
<th>p‑value</th>
<th>95% CI (lower)</th>
<th>95% CI (upper)</th>
<th>Mean Adult</th>
<th>Mean Juvenile</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Rubble_L</td>
<td>1.7443</td>
<td>36.368</td>
<td>0.0896</td>
<td>−4.253</td>
<td>56.672</td>
<td>38.298</td>
<td>12.088</td>
</tr>
<tr class="even">
<td>Turf_L</td>
<td>−2.0783</td>
<td>36.279</td>
<td>0.0448</td>
<td>−60.349</td>
<td>−0.746</td>
<td>18.928</td>
<td>49.475</td>
</tr>
<tr class="odd">
<td>Macro_L</td>
<td>1.4270</td>
<td>18.380</td>
<td>0.1704</td>
<td>−4.077</td>
<td>21.419</td>
<td>7.400</td>
<td>−1.272</td>
</tr>
</tbody>
</table>
</section>
<section id="c-spil-conspecific-substrate-differences-adult-vs-juvenile" class="level1">
<h1>C spil conspecific substrate differences (adult vs juvenile)</h1>
<table class="caption-top table">
<colgroup>
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 7%">
<col style="width: 9%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 11%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>Substrate</th>
<th>t statistic</th>
<th>df</th>
<th>p‑value</th>
<th>95% CI (lower)</th>
<th>95% CI (upper)</th>
<th>Mean Adult</th>
<th>Mean Juvenile</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Rubble_L</td>
<td>1.6118</td>
<td>35.510</td>
<td>0.1159</td>
<td>−5.009</td>
<td>43.699</td>
<td>21.902</td>
<td>2.557</td>
</tr>
<tr class="even">
<td>Sand_L</td>
<td>2.9436</td>
<td>22.197</td>
<td>0.0075</td>
<td>5.307</td>
<td>30.571</td>
<td>−19.713</td>
<td>−37.652</td>
</tr>
<tr class="odd">
<td>Turf_L</td>
<td>−3.0699</td>
<td>37.950</td>
<td>0.0039</td>
<td>−69.288</td>
<td>−14.219</td>
<td>20.529</td>
<td>62.283</td>
</tr>
</tbody>
</table>
</section>
<section id="z-corn-conspecific-substrate-differences-adult-vs-juvenile" class="level1">
<h1>Z corn conspecific substrate differences (adult vs juvenile)</h1>
<table class="caption-top table">
<colgroup>
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 7%">
<col style="width: 9%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 11%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>Substrate</th>
<th>t statistic</th>
<th>df</th>
<th>p‑value</th>
<th>95% CI (lower)</th>
<th>95% CI (upper)</th>
<th>Mean Adult</th>
<th>Mean Juvenile</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Rubble_L</td>
<td>−1.5311</td>
<td>23.198</td>
<td>0.1393</td>
<td>−51.276</td>
<td>7.645</td>
<td>2.500</td>
<td>24.316</td>
</tr>
<tr class="even">
<td>Turf_L</td>
<td>−0.0037</td>
<td>24.970</td>
<td>0.9971</td>
<td>−28.293</td>
<td>28.192</td>
<td>19.087</td>
<td>19.137</td>
</tr>
<tr class="odd">
<td>Sponge_L</td>
<td>1.3999</td>
<td>16.393</td>
<td>0.1802</td>
<td>−8.178</td>
<td>40.161</td>
<td>27.729</td>
<td>11.738</td>
</tr>
</tbody>
</table>
</section>
<section id="heterospecific-substrate-preferences-juveniles-and-adults" class="level1">
<h1>Heterospecific Substrate preferences (Juveniles and adults)</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co">#With this I will compare the substrate preferences of juveniles across species and adults across species</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>Juvenile <span class="ot">&lt;-</span> strauss_results_indv <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Age_Class <span class="sc">==</span> <span class="st">"Juvenile"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>()</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>Adult <span class="ot">&lt;-</span> strauss_results_indv <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Age_Class <span class="sc">==</span> <span class="st">"Adult"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>() </span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a><span class="co">#Juveniles</span></span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Rubble_L</span></span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a>rubble_aov_j <span class="ot">&lt;-</span> <span class="fu">aov</span>(Rubble_L <span class="sc">~</span> Species, <span class="at">data =</span> Juvenile)</span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(rubble_aov_j)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Df Sum Sq Mean Sq F value Pr(&gt;F)
Species      2   4628    2314   1.529  0.226
Residuals   56  84774    1514               </code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">TukeyHSD</span>(rubble_aov_j)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = Rubble_L ~ Species, data = Juvenile)

$Species
                             diff        lwr      upr     p adj
C spilurus-A triostegus -9.531445 -39.153447 20.09056 0.7199977
Z cornutus-A triostegus 12.227515 -17.781719 42.23675 0.5918328
Z cornutus-C spilurus   21.758961  -8.250273 51.76819 0.1974985</code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Sand_L</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>sand_aov_j <span class="ot">&lt;-</span> <span class="fu">aov</span>(Sand_L <span class="sc">~</span> Species, <span class="at">data =</span> Juvenile)</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(sand_aov_j)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Df Sum Sq Mean Sq F value   Pr(&gt;F)    
Species      2   1834   917.1   11.05 9.04e-05 ***
Residuals   56   4650    83.0                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">TukeyHSD</span>(sand_aov_j)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = Sand_L ~ Species, data = Juvenile)

$Species
                             diff       lwr       upr     p adj
C spilurus-A triostegus  2.372029 -4.565318  9.309376 0.6903165
Z cornutus-A triostegus 12.934591  5.906556 19.962626 0.0001292
Z cornutus-C spilurus   10.562562  3.534527 17.590597 0.0018191</code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Turf_L</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>turf_aov_j <span class="ot">&lt;-</span> <span class="fu">aov</span>(Turf_L <span class="sc">~</span> Species, <span class="at">data =</span> Juvenile)</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(turf_aov_j)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Df Sum Sq Mean Sq F value Pr(&gt;F)  
Species      2  19029    9515   4.768 0.0122 *
Residuals   56 111744    1995                 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">TukeyHSD</span>(turf_aov_j)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = Turf_L ~ Species, data = Juvenile)

$Species
                             diff       lwr       upr     p adj
C spilurus-A triostegus  12.80717 -21.20203 46.816357 0.6384067
Z cornutus-A triostegus -30.33811 -64.79188  4.115667 0.0949112
Z cornutus-C spilurus   -43.14527 -77.59905 -8.691498 0.0106117</code></pre>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Macro_L</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>macro_aov_j <span class="ot">&lt;-</span> <span class="fu">aov</span>(Macro_L <span class="sc">~</span> Species, <span class="at">data =</span> Juvenile)</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(macro_aov_j)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Df Sum Sq Mean Sq F value   Pr(&gt;F)    
Species      2  68.14   34.07    8.85 0.000457 ***
Residuals   56 215.60    3.85                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">TukeyHSD</span>(macro_aov_j)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = Macro_L ~ Species, data = Juvenile)

$Species
                              diff       lwr        upr     p adj
C spilurus-A triostegus  0.4843177 -1.009533  1.9781684 0.7164340
Z cornutus-A triostegus -2.0179220 -3.531301 -0.5045430 0.0061301
Z cornutus-C spilurus   -2.5022396 -4.015619 -0.9888607 0.0005782</code></pre>
</div>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Sponge_L</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>sponge_aov_j <span class="ot">&lt;-</span> <span class="fu">aov</span>(Sponge_L <span class="sc">~</span> Species, <span class="at">data =</span> Juvenile)</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(sponge_aov_j)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Df Sum Sq Mean Sq F value  Pr(&gt;F)   
Species      2   1775   887.3   5.705 0.00556 **
Residuals   56   8710   155.5                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">TukeyHSD</span>(sponge_aov_j)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = Sponge_L ~ Species, data = Juvenile)

$Species
                                 diff       lwr       upr     p adj
C spilurus-A triostegus -1.376677e-14 -9.495122  9.495122 1.0000000
Z cornutus-A triostegus  1.173763e+01  2.118381 21.356874 0.0130969
Z cornutus-C spilurus    1.173763e+01  2.118381 21.356874 0.0130969</code></pre>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Adults</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Rubble_L</span></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>rubble_aov <span class="ot">&lt;-</span> <span class="fu">aov</span>(Rubble_L <span class="sc">~</span> Species, <span class="at">data =</span> Adult)</span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(rubble_aov)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Df Sum Sq Mean Sq F value Pr(&gt;F)  
Species      2   9504    4752   2.428  0.099 .
Residuals   48  93935    1957                 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">TukeyHSD</span>(rubble_aov)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = Rubble_L ~ Species, data = Adult)

$Species
                             diff       lwr       upr     p adj
C spilurus-A triostegus -16.39595 -50.67100 17.879107 0.4844205
Z cornutus-A triostegus -35.79803 -75.24839  3.652341 0.0823369
Z cornutus-C spilurus   -19.40208 -58.46880 19.664643 0.4583264</code></pre>
</div>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Sand_L</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>sand_aov <span class="ot">&lt;-</span> <span class="fu">aov</span>(Sand_L <span class="sc">~</span> Species, <span class="at">data =</span> Adult)</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(sand_aov)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Df Sum Sq Mean Sq F value   Pr(&gt;F)    
Species      2   5733  2866.5   9.916 0.000249 ***
Residuals   48  13876   289.1                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">TukeyHSD</span>(sand_aov)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = Sand_L ~ Species, data = Adult)

$Species
                             diff        lwr      upr     p adj
C spilurus-A triostegus 20.155214   6.981845 33.32858 0.0015803
Z cornutus-A triostegus 24.243421   9.080957 39.40589 0.0009504
Z cornutus-C spilurus    4.088207 -10.926807 19.10322 0.7884723</code></pre>
</div>
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Turf_L</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>turf_aov <span class="ot">&lt;-</span> <span class="fu">aov</span>(Turf_L <span class="sc">~</span> Species, <span class="at">data =</span> Adult)</span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(turf_aov)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Df Sum Sq Mean Sq F value Pr(&gt;F)
Species      2     29    14.5   0.009  0.991
Residuals   48  78859  1642.9               </code></pre>
</div>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">TukeyHSD</span>(turf_aov)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = Turf_L ~ Species, data = Adult)

$Species
                              diff       lwr      upr     p adj
C spilurus-A triostegus  1.6013706 -29.80298 33.00572 0.9916518
Z cornutus-A triostegus  0.1588559 -35.98736 36.30507 0.9999377
Z cornutus-C spilurus   -1.4425147 -37.23721 34.35219 0.9947771</code></pre>
</div>
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Macro_L</span></span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>macro_aov <span class="ot">&lt;-</span> <span class="fu">aov</span>(Macro_L <span class="sc">~</span> Species, <span class="at">data =</span> Adult)</span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(macro_aov)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Df Sum Sq Mean Sq F value Pr(&gt;F)  
Species      2   1335   667.5   2.555 0.0882 .
Residuals   48  12540   261.3                 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">TukeyHSD</span>(macro_aov)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = Macro_L ~ Species, data = Adult)

$Species
                              diff       lwr       upr     p adj
C spilurus-A triostegus  -9.974109 -22.49742  2.549198 0.1423459
Z cornutus-A triostegus -11.427325 -25.84157  2.986921 0.1447988
Z cornutus-C spilurus    -1.453216 -15.72729 12.820856 0.9671548</code></pre>
</div>
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Sponge_L</span></span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>sponge_aov <span class="ot">&lt;-</span> <span class="fu">aov</span>(Sponge_L <span class="sc">~</span> Species, <span class="at">data =</span> Adult)</span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(sponge_aov)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Df Sum Sq Mean Sq F value   Pr(&gt;F)    
Species      2   7329    3664   12.64 3.88e-05 ***
Residuals   48  13910     290                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">TukeyHSD</span>(sponge_aov)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = Sponge_L ~ Species, data = Adult)

$Species
                            diff       lwr      upr     p adj
C spilurus-A triostegus -1.00000 -14.18934 12.18934 0.9816416
Z cornutus-A triostegus 27.72894  12.54810 42.90978 0.0001653
Z cornutus-C spilurus   28.72894  13.69572 43.76215 0.0000845</code></pre>
</div>
</div>
</section>
<section id="anova-heterospecific-juvenile-species-substrate-preference" class="level1">
<h1>Anova Heterospecific juvenile species substrate preference</h1>
<table class="caption-top table">
<colgroup>
<col style="width: 13%">
<col style="width: 14%">
<col style="width: 18%">
<col style="width: 19%">
<col style="width: 9%">
<col style="width: 10%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>Substrate</th>
<th>Df (Species)</th>
<th>Sum Sq (Species)</th>
<th>Mean Sq (Species)</th>
<th>F value</th>
<th>Pr(&gt;F)</th>
<th>Significance</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Rubble_L</td>
<td>2</td>
<td>4628</td>
<td>2314</td>
<td>1.529</td>
<td>0.226</td>
<td>n.s.</td>
</tr>
<tr class="even">
<td>Sand_L</td>
<td>2</td>
<td>1834</td>
<td>917.1</td>
<td>11.05</td>
<td>9.04e-05</td>
<td>***</td>
</tr>
<tr class="odd">
<td>Turf_L</td>
<td>2</td>
<td>19029</td>
<td>9515</td>
<td>4.768</td>
<td>0.0122</td>
<td>*</td>
</tr>
<tr class="even">
<td>Macro_L</td>
<td>2</td>
<td>68.14</td>
<td>34.07</td>
<td>8.85</td>
<td>0.000457</td>
<td>***</td>
</tr>
<tr class="odd">
<td>Sponge_L</td>
<td>2</td>
<td>1775</td>
<td>887.3</td>
<td>5.705</td>
<td>0.00556</td>
<td>**</td>
</tr>
</tbody>
</table>
<p>*** = p &lt; 0.001 ** = p &lt; 0.01 * = p &lt; 0.05 . = p &lt; 0.1 (trend)</p>
<p>Significant differences mean that they did not both share/ like feeding on the substrate</p>
</section>
<section id="tukey-heterospecific-juvenile-species-substrate-preference" class="level1">
<h1>Tukey Heterospecific juvenile species substrate preference</h1>
<table class="caption-top table">
<colgroup>
<col style="width: 10%">
<col style="width: 24%">
<col style="width: 11%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 17%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th>Substrate</th>
<th>Comparison</th>
<th>Difference</th>
<th>Lower CI</th>
<th>Upper CI</th>
<th>Adjusted p-value</th>
<th>Significance</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Rubble_L</td>
<td>C. spilurus – A. triostegus</td>
<td>-9.53</td>
<td>-39.15</td>
<td>20.09</td>
<td>0.7200</td>
<td>n.s.</td>
</tr>
<tr class="even">
<td>Rubble_L</td>
<td>Z. cornutus – A. triostegus</td>
<td>12.23</td>
<td>-17.78</td>
<td>42.24</td>
<td>0.5918</td>
<td>n.s.</td>
</tr>
<tr class="odd">
<td>Rubble_L</td>
<td>Z. cornutus – C. spilurus</td>
<td>21.76</td>
<td>-8.25</td>
<td>51.77</td>
<td>0.1975</td>
<td>n.s.</td>
</tr>
<tr class="even">
<td>Sand_L</td>
<td>C. spilurus – A. triostegus</td>
<td>2.37</td>
<td>-4.57</td>
<td>9.31</td>
<td>0.6903</td>
<td>n.s.</td>
</tr>
<tr class="odd">
<td>Sand_L</td>
<td>Z. cornutus – A. triostegus</td>
<td>12.93</td>
<td>5.91</td>
<td>19.96</td>
<td>0.00013</td>
<td>***</td>
</tr>
<tr class="even">
<td>Sand_L</td>
<td>Z. cornutus – C. spilurus</td>
<td>10.56</td>
<td>3.53</td>
<td>17.59</td>
<td>0.00182</td>
<td>**</td>
</tr>
<tr class="odd">
<td>Turf_L</td>
<td>C. spilurus – A. triostegus</td>
<td>12.81</td>
<td>-21.20</td>
<td>46.82</td>
<td>0.6384</td>
<td>n.s.</td>
</tr>
<tr class="even">
<td>Turf_L</td>
<td>Z. cornutus – A. triostegus</td>
<td>-30.34</td>
<td>-64.79</td>
<td>4.12</td>
<td>0.0949</td>
<td>. (trend)</td>
</tr>
<tr class="odd">
<td>Turf_L</td>
<td>Z. cornutus – C. spilurus</td>
<td>-43.15</td>
<td>-77.60</td>
<td>-8.69</td>
<td>0.0106</td>
<td>*</td>
</tr>
<tr class="even">
<td>Macro_L</td>
<td>C. spilurus – A. triostegus</td>
<td>0.48</td>
<td>-1.01</td>
<td>1.98</td>
<td>0.7164</td>
<td>n.s.</td>
</tr>
<tr class="odd">
<td>Macro_L</td>
<td>Z. cornutus – A. triostegus</td>
<td>-2.02</td>
<td>-3.53</td>
<td>-0.50</td>
<td>0.00613</td>
<td>**</td>
</tr>
<tr class="even">
<td>Macro_L</td>
<td>Z. cornutus – C. spilurus</td>
<td>-2.50</td>
<td>-4.02</td>
<td>-0.99</td>
<td>0.00058</td>
<td>***</td>
</tr>
<tr class="odd">
<td>Sponge_L</td>
<td>C. spilurus – A. triostegus</td>
<td>~0.00</td>
<td>-9.50</td>
<td>9.50</td>
<td>1.0000</td>
<td>n.s.</td>
</tr>
<tr class="even">
<td>Sponge_L</td>
<td>Z. cornutus – A. triostegus</td>
<td>11.74</td>
<td>2.12</td>
<td>21.36</td>
<td>0.0131</td>
<td>*</td>
</tr>
<tr class="odd">
<td>Sponge_L</td>
<td>Z. cornutus – C. spilurus</td>
<td>11.74</td>
<td>2.12</td>
<td>21.36</td>
<td>0.0131</td>
<td>*</td>
</tr>
</tbody>
</table>
</section>
<section id="anova-heterospecific-adult-species-substrate-preference" class="level1">
<h1>Anova Heterospecific adult species substrate preference</h1>
<table class="caption-top table">
<colgroup>
<col style="width: 13%">
<col style="width: 14%">
<col style="width: 18%">
<col style="width: 19%">
<col style="width: 9%">
<col style="width: 11%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>Substrate</th>
<th>Df (Species)</th>
<th>Sum Sq (Species)</th>
<th>Mean Sq (Species)</th>
<th>F value</th>
<th>Pr(&gt;F)</th>
<th>Significance</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Rubble_L</td>
<td>2</td>
<td>9504</td>
<td>4752</td>
<td>2.428</td>
<td>0.099</td>
<td>. (trend)</td>
</tr>
<tr class="even">
<td>Sand_L</td>
<td>2</td>
<td>5733</td>
<td>2866.5</td>
<td>9.916</td>
<td>0.000249</td>
<td>***</td>
</tr>
<tr class="odd">
<td>Turf_L</td>
<td>2</td>
<td>29</td>
<td>14.5</td>
<td>0.009</td>
<td>0.991</td>
<td>n.s.</td>
</tr>
<tr class="even">
<td>Macro_L</td>
<td>2</td>
<td>1335</td>
<td>667.5</td>
<td>2.555</td>
<td>0.0882</td>
<td>. (trend)</td>
</tr>
<tr class="odd">
<td>Sponge_L</td>
<td>2</td>
<td>7329</td>
<td>3664</td>
<td>12.64</td>
<td>3.88e-05</td>
<td>***</td>
</tr>
</tbody>
</table>
<p>*** = p &lt; 0.001 ** = p &lt; 0.01 * = p &lt; 0.05 . = p &lt; 0.1 (trend)</p>
</section>
<section id="tukey-heterospecific-adult-species-substrate-preference" class="level1">
<h1>Tukey Heterospecific adult species substrate preference</h1>
<table class="caption-top table">
<colgroup>
<col style="width: 10%">
<col style="width: 24%">
<col style="width: 11%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 17%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th>Substrate</th>
<th>Comparison</th>
<th>Difference</th>
<th>Lower CI</th>
<th>Upper CI</th>
<th>Adjusted p-value</th>
<th>Significance</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Rubble_L</td>
<td>C. spilurus – A. triostegus</td>
<td>-16.40</td>
<td>-50.67</td>
<td>17.88</td>
<td>0.4844</td>
<td>n.s.</td>
</tr>
<tr class="even">
<td>Rubble_L</td>
<td>Z. cornutus – A. triostegus</td>
<td>-35.80</td>
<td>-75.25</td>
<td>3.65</td>
<td>0.0823</td>
<td>. (trend)</td>
</tr>
<tr class="odd">
<td>Rubble_L</td>
<td>Z. cornutus – C. spilurus</td>
<td>-19.40</td>
<td>-58.47</td>
<td>19.66</td>
<td>0.4583</td>
<td>n.s.</td>
</tr>
<tr class="even">
<td>Sand_L</td>
<td>C. spilurus – A. triostegus</td>
<td>20.16</td>
<td>6.98</td>
<td>33.33</td>
<td>0.0016</td>
<td>**</td>
</tr>
<tr class="odd">
<td>Sand_L</td>
<td>Z. cornutus – A. triostegus</td>
<td>24.24</td>
<td>9.08</td>
<td>39.41</td>
<td>0.00095</td>
<td>***</td>
</tr>
<tr class="even">
<td>Sand_L</td>
<td>Z. cornutus – C. spilurus</td>
<td>4.09</td>
<td>-10.93</td>
<td>19.10</td>
<td>0.7885</td>
<td>n.s.</td>
</tr>
<tr class="odd">
<td>Turf_L</td>
<td>C. spilurus – A. triostegus</td>
<td>1.60</td>
<td>-29.80</td>
<td>33.01</td>
<td>0.9917</td>
<td>n.s.</td>
</tr>
<tr class="even">
<td>Turf_L</td>
<td>Z. cornutus – A. triostegus</td>
<td>0.16</td>
<td>-35.99</td>
<td>36.31</td>
<td>0.9999</td>
<td>n.s.</td>
</tr>
<tr class="odd">
<td>Turf_L</td>
<td>Z. cornutus – C. spilurus</td>
<td>-1.44</td>
<td>-37.24</td>
<td>34.35</td>
<td>0.9948</td>
<td>n.s.</td>
</tr>
<tr class="even">
<td>Macro_L</td>
<td>C. spilurus – A. triostegus</td>
<td>-9.97</td>
<td>-22.50</td>
<td>2.55</td>
<td>0.1423</td>
<td>n.s.</td>
</tr>
<tr class="odd">
<td>Macro_L</td>
<td>Z. cornutus – A. triostegus</td>
<td>-11.43</td>
<td>-25.84</td>
<td>2.99</td>
<td>0.1448</td>
<td>n.s.</td>
</tr>
<tr class="even">
<td>Macro_L</td>
<td>Z. cornutus – C. spilurus</td>
<td>-1.45</td>
<td>-15.73</td>
<td>12.82</td>
<td>0.9672</td>
<td>n.s.</td>
</tr>
<tr class="odd">
<td>Sponge_L</td>
<td>C. spilurus – A. triostegus</td>
<td>-1.00</td>
<td>-14.19</td>
<td>12.19</td>
<td>0.9816</td>
<td>n.s.</td>
</tr>
<tr class="even">
<td>Sponge_L</td>
<td>Z. cornutus – A. triostegus</td>
<td>27.73</td>
<td>12.55</td>
<td>42.91</td>
<td>0.00017</td>
<td>***</td>
</tr>
<tr class="odd">
<td>Sponge_L</td>
<td>Z. cornutus – C. spilurus</td>
<td>28.73</td>
<td>13.70</td>
<td>43.76</td>
<td>0.00008</td>
<td>***</td>
</tr>
</tbody>
</table>
</section>
<section id="anova" class="level1">
<h1>ANOVA</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Let's see the mean bite rate for each species</span></span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a>Bites <span class="sc">%&gt;%</span></span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Species) <span class="sc">%&gt;%</span> <span class="co"># Group by species</span></span>
<span id="cb70-4"><a href="#cb70-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean_bites =</span> <span class="fu">mean</span>(Bites_per_min), <span class="co"># Calculate mean and standard deviation of bites per minute</span></span>
<span id="cb70-5"><a href="#cb70-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">sd_bites =</span> <span class="fu">sd</span>(Bites_per_min),</span>
<span id="cb70-6"><a href="#cb70-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">n =</span> <span class="fu">n</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 4
  Species      mean_bites sd_bites     n
  &lt;chr&gt;             &lt;dbl&gt;    &lt;dbl&gt; &lt;int&gt;
1 A triostegus      39.9     22.3     40
2 C spilurus        20.4     11.3     40
3 Z cornutus         1.53     2.07    40</code></pre>
</div>
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="co"># One-way ANOVA: Does bite rate differ by species?</span></span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a><span class="co"># aov() runs the ANOVA</span></span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Formula format: continuous_variable ~ grouping_variable</span></span>
<span id="cb72-4"><a href="#cb72-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-5"><a href="#cb72-5" aria-hidden="true" tabindex="-1"></a>bite_anova <span class="ot">&lt;-</span> <span class="fu">aov</span>(Bites_per_min <span class="sc">~</span> Species, <span class="at">data =</span> Bites)</span>
<span id="cb72-6"><a href="#cb72-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-7"><a href="#cb72-7" aria-hidden="true" tabindex="-1"></a><span class="co"># summary() shows the ANOVA results</span></span>
<span id="cb72-8"><a href="#cb72-8" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(bite_anova)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Df Sum Sq Mean Sq F value Pr(&gt;F)    
Species       2  29425   14712   69.95 &lt;2e-16 ***
Residuals   117  24608     210                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Which species are different from eachother?</span></span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Tukey's Honest Significant Difference test</span></span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a><span class="co"># compares every pair of species to each other</span></span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-5"><a href="#cb74-5" aria-hidden="true" tabindex="-1"></a><span class="fu">TukeyHSD</span>(bite_anova)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = Bites_per_min ~ Species, data = Bites)

$Species
                             diff       lwr       upr p adj
C spilurus-A triostegus -19.50833 -27.20669 -11.80998 1e-07
Z cornutus-A triostegus -38.35476 -46.05312 -30.65641 0e+00
Z cornutus-C spilurus   -18.84643 -26.54478 -11.14807 2e-07</code></pre>
</div>
</div>
<section id="tukey-hsd-results-summary" class="level2">
<h2 class="anchored" data-anchor-id="tukey-hsd-results-summary">Tukey HSD Results Summary</h2>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Comparison</th>
<th>Difference</th>
<th>p-value</th>
<th>Result</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>C spilurus vs A triostegus</td>
<td>-19.51</td>
<td>&lt; 0.001</td>
<td>Significant</td>
</tr>
<tr class="even">
<td>Z cornutus vs A triostegus</td>
<td>-38.35</td>
<td>&lt; 0.001</td>
<td>Significant</td>
</tr>
<tr class="odd">
<td>Z cornutus vs C spilurus</td>
<td>-18.85</td>
<td>&lt; 0.001</td>
<td>Significant</td>
</tr>
</tbody>
</table>
</section>
<section id="way-anova" class="level2">
<h2 class="anchored" data-anchor-id="way-anova">2-way ANOVA</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Two-way ANOVA: Does bite rate differ by species AND age class?</span></span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a><span class="co"># The * between Species and Age_Class tests:</span></span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a><span class="co">#   1. Main effect of Species</span></span>
<span id="cb76-4"><a href="#cb76-4" aria-hidden="true" tabindex="-1"></a><span class="co">#   2. Main effect of Age_Class</span></span>
<span id="cb76-5"><a href="#cb76-5" aria-hidden="true" tabindex="-1"></a><span class="co">#   3. Interaction between Species and Age_Class</span></span>
<span id="cb76-6"><a href="#cb76-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-7"><a href="#cb76-7" aria-hidden="true" tabindex="-1"></a>bite_anova_2way <span class="ot">&lt;-</span> <span class="fu">aov</span>(Bites_per_min <span class="sc">~</span> Species <span class="sc">*</span> Age_Class, <span class="at">data =</span> Bites)</span>
<span id="cb76-8"><a href="#cb76-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-9"><a href="#cb76-9" aria-hidden="true" tabindex="-1"></a><span class="co"># View results</span></span>
<span id="cb76-10"><a href="#cb76-10" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(bite_anova_2way)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   Df Sum Sq Mean Sq F value   Pr(&gt;F)    
Species             2  29425   14712  81.624  &lt; 2e-16 ***
Age_Class           1   3005    3005  16.673 8.28e-05 ***
Species:Age_Class   2   1055     528   2.927   0.0576 .  
Residuals         114  20548     180                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</section>
<section id="two-way-anova-results-bite-rate-by-species-and-age-class" class="level2">
<h2 class="anchored" data-anchor-id="two-way-anova-results-bite-rate-by-species-and-age-class">Two-Way ANOVA Results: Bite Rate by Species and Age Class</h2>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Effect</th>
<th>Df</th>
<th>Sum Sq</th>
<th>Mean Sq</th>
<th>F value</th>
<th>p-value</th>
<th>Significance</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Species</td>
<td>2</td>
<td>29425</td>
<td>14712</td>
<td>81.62</td>
<td>&lt; 0.001</td>
<td>***</td>
</tr>
<tr class="even">
<td>Age Class</td>
<td>1</td>
<td>3005</td>
<td>3005</td>
<td>16.67</td>
<td>&lt; 0.001</td>
<td>***</td>
</tr>
<tr class="odd">
<td>Species × Age Class</td>
<td>2</td>
<td>1055</td>
<td>528</td>
<td>2.93</td>
<td>0.058</td>
<td>.</td>
</tr>
<tr class="even">
<td>Residuals</td>
<td>114</td>
<td>20548</td>
<td>180</td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p>Significance codes: *** p &lt; 0.001, ** p &lt; 0.01, * p &lt; 0.05, . p &lt; 0.1</p>
<p><strong>Summary:</strong> Both species and age class had significant effects on bite rate (p &lt; 0.001). The interaction between species and age class was marginally non-significant (p = 0.058), suggesting the difference between adults and juveniles may vary somewhat across species.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="co"># See mean bite rates for each species AND age class combination</span></span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a>Bites <span class="sc">%&gt;%</span></span>
<span id="cb78-3"><a href="#cb78-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Species, Age_Class) <span class="sc">%&gt;%</span></span>
<span id="cb78-4"><a href="#cb78-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb78-5"><a href="#cb78-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_bites =</span> <span class="fu">mean</span>(Bites_per_min),</span>
<span id="cb78-6"><a href="#cb78-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">sd_bites =</span> <span class="fu">sd</span>(Bites_per_min),</span>
<span id="cb78-7"><a href="#cb78-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">n</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'Species'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
# Groups:   Species [3]
  Species      Age_Class mean_bites sd_bites     n
  &lt;chr&gt;        &lt;chr&gt;          &lt;dbl&gt;    &lt;dbl&gt; &lt;int&gt;
1 A triostegus Adult         31.9     26.0      20
2 A triostegus Juvenile      47.9     14.6      20
3 C spilurus   Adult         14.4      8.45     20
4 C spilurus   Juvenile      26.4     10.7      20
5 Z cornutus   Adult          0.557    0.885    20
6 Z cornutus   Juvenile       2.5      2.46     20</code></pre>
</div>
</div>
</section>
</section>
<section id="time-foraging" class="level1">
<h1>Time Foraging</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a>Time_Foraging_clean<span class="ot">&lt;-</span> Time_Foraging <span class="sc">%&gt;%</span> <span class="co"># clean the data </span></span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>( <span class="co"># Select and rename the columns</span></span>
<span id="cb81-3"><a href="#cb81-3" aria-hidden="true" tabindex="-1"></a>    Species,</span>
<span id="cb81-4"><a href="#cb81-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">Size =</span> <span class="st">`</span><span class="at">Size (cm)</span><span class="st">`</span>,</span>
<span id="cb81-5"><a href="#cb81-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">Age_Class =</span> <span class="st">`</span><span class="at">Age Class</span><span class="st">`</span>,</span>
<span id="cb81-6"><a href="#cb81-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">Mean_Bout_Duration =</span> <span class="st">`</span><span class="at">Mean Feeding Bout Duration (seconds)</span><span class="st">`</span>,</span>
<span id="cb81-7"><a href="#cb81-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">Bout_Frequency =</span> <span class="st">`</span><span class="at">Feeding Bout Frequency (Mean per min)</span><span class="st">`</span>,</span>
<span id="cb81-8"><a href="#cb81-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">Prop_Time_Feeding =</span> <span class="st">`</span><span class="at">Proportion of Time Feeding</span><span class="st">`</span>)</span>
<span id="cb81-9"><a href="#cb81-9" aria-hidden="true" tabindex="-1"></a>Time_Foraging_clean</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 30 × 6
   Species    Size Age_Class Mean_Bout_Duration Bout_Frequency Prop_Time_Feeding
   &lt;chr&gt;     &lt;dbl&gt; &lt;chr&gt;                  &lt;dbl&gt;          &lt;dbl&gt;             &lt;dbl&gt;
 1 Z cornut…   8   Juvenile                1.3           0.42               0.91
 2 Z cornut…   8.5 Juvenile                3.2           0.714              3.81
 3 Z cornut…  10   Juvenile                7.5           1.14              14.2 
 4 Z cornut…   7   Juvenile                1.3           0.42               0.91
 5 Z cornut…   9.5 Juvenile                6.8           1.42              16.1 
 6 Z cornut…   9   Juvenile                6.25          1.14              11.9 
 7 Z cornut…   6.5 Juvenile               11             0.714             13.1 
 8 Z cornut…   7   Juvenile               12.7           0.86              18.1 
 9 Z cornut…   6.5 Juvenile               25.2           0.714             30.0 
10 Z cornut…   5.5 Juvenile               22.4           1                 37.3 
# ℹ 20 more rows</code></pre>
</div>
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate mean proportion of time feeding for each sp- I know this is already in the data but just double checking </span></span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb83-3"><a href="#cb83-3" aria-hidden="true" tabindex="-1"></a>Time_Foraging_clean <span class="sc">%&gt;%</span></span>
<span id="cb83-4"><a href="#cb83-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Species) <span class="sc">%&gt;%</span></span>
<span id="cb83-5"><a href="#cb83-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb83-6"><a href="#cb83-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_prop_time =</span> <span class="fu">mean</span>(Prop_Time_Feeding),</span>
<span id="cb83-7"><a href="#cb83-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">sd_prop_time =</span> <span class="fu">sd</span>(Prop_Time_Feeding),</span>
<span id="cb83-8"><a href="#cb83-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">n</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 4
  Species      mean_prop_time sd_prop_time     n
  &lt;chr&gt;                 &lt;dbl&gt;        &lt;dbl&gt; &lt;int&gt;
1 A triostegus           74.8         13.3    10
2 C spillurus            62.8         12.2    10
3 Z cornutus             14.6         11.9    10</code></pre>
</div>
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The pattern is the same as the Bite Rate data -&gt; in table below</span></span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb85-3"><a href="#cb85-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Fix the spelling of C spillurus to match the Bite Rate data</span></span>
<span id="cb85-4"><a href="#cb85-4" aria-hidden="true" tabindex="-1"></a>Time_Foraging_clean <span class="ot">&lt;-</span> Time_Foraging_clean <span class="sc">%&gt;%</span></span>
<span id="cb85-5"><a href="#cb85-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Species =</span> <span class="fu">case_when</span>(Species <span class="sc">==</span> <span class="st">"C spillurus"</span> <span class="sc">~</span> <span class="st">"C spilurus"</span>, <span class="co"># fix name </span></span>
<span id="cb85-6"><a href="#cb85-6" aria-hidden="true" tabindex="-1"></a>    <span class="cn">TRUE</span> <span class="sc">~</span> Species))</span>
<span id="cb85-7"><a href="#cb85-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb85-8"><a href="#cb85-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Verify the fix</span></span>
<span id="cb85-9"><a href="#cb85-9" aria-hidden="true" tabindex="-1"></a>Time_Foraging_clean <span class="sc">%&gt;%</span></span>
<span id="cb85-10"><a href="#cb85-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Species) <span class="sc">%&gt;%</span></span>
<span id="cb85-11"><a href="#cb85-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">n</span>()) <span class="co"># should be C spilurus w/ n=10</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 2
  Species          n
  &lt;chr&gt;        &lt;int&gt;
1 A triostegus    10
2 C spilurus      10
3 Z cornutus      10</code></pre>
</div>
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="co"># One-way ANOVA: Does proportion of time feeding differ by species?</span></span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a>time_forage_anova <span class="ot">&lt;-</span> <span class="fu">aov</span>(Prop_Time_Feeding <span class="sc">~</span> Species, <span class="at">data =</span> Time_Foraging_clean)</span>
<span id="cb87-3"><a href="#cb87-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb87-4"><a href="#cb87-4" aria-hidden="true" tabindex="-1"></a><span class="co"># View results</span></span>
<span id="cb87-5"><a href="#cb87-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(time_forage_anova)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Df Sum Sq Mean Sq F value   Pr(&gt;F)    
Species      2  20294   10147   65.37 4.48e-11 ***
Residuals   27   4191     155                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Tukey's test: Which species differ from each other?</span></span>
<span id="cb89-2"><a href="#cb89-2" aria-hidden="true" tabindex="-1"></a><span class="fu">TukeyHSD</span>(time_forage_anova)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = Prop_Time_Feeding ~ Species, data = Time_Foraging_clean)

$Species
                             diff       lwr        upr     p adj
C spilurus-A triostegus -12.06758 -25.88254   1.747377 0.0955794
Z cornutus-A triostegus -60.20797 -74.02293 -46.393007 0.0000000
Z cornutus-C spilurus   -48.14038 -61.95534 -34.325423 0.0000000</code></pre>
</div>
</div>
<section id="comparison-of-feeding-metrics-across-species-juveniles-only" class="level2">
<h2 class="anchored" data-anchor-id="comparison-of-feeding-metrics-across-species-juveniles-only">Comparison of Feeding Metrics Across Species (Juveniles Only)</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 11%">
<col style="width: 35%">
<col style="width: 6%">
<col style="width: 31%">
<col style="width: 6%">
<col style="width: 7%">
</colgroup>
<thead>
<tr class="header">
<th>Species</th>
<th>Mean Bite Rate (bites/min)</th>
<th>SD</th>
<th>Mean Time Foraging (%)</th>
<th>SD</th>
<th>Rank</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>A triostegus</td>
<td>47.9</td>
<td>14.6</td>
<td>74.8</td>
<td>13.3</td>
<td>Highest</td>
</tr>
<tr class="even">
<td>C spilurus</td>
<td>26.4</td>
<td>10.7</td>
<td>62.8</td>
<td>12.2</td>
<td>Middle</td>
</tr>
<tr class="odd">
<td>Z cornutus</td>
<td>2.5</td>
<td>2.5</td>
<td>14.6</td>
<td>11.9</td>
<td>Lowest</td>
</tr>
</tbody>
</table>
<p><strong>Summary:</strong> Species showed consistent ranking across both feeding metrics. A triostegus (Manini) had the highest bite rate and spent the most time foraging, while Z cornutus (Moorish Idol) had the lowest values for both measures. This suggests that species with higher bite rates also allocate more time to foraging behavior.</p>
</section>
<section id="side-by-side-anova-comparison-bite-rate-vs.-time-foraging" class="level2">
<h2 class="anchored" data-anchor-id="side-by-side-anova-comparison-bite-rate-vs.-time-foraging">Side-by-Side ANOVA Comparison: Bite Rate vs.&nbsp;Time Foraging</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 22%">
<col style="width: 7%">
<col style="width: 11%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Feeding Metric</th>
<th>Df</th>
<th>Sum Sq</th>
<th>Mean Sq</th>
<th>F value</th>
<th>p-value</th>
<th>Significance</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Bite Rate</td>
<td>2</td>
<td>29425</td>
<td>14712</td>
<td>69.95</td>
<td>&lt; 0.001</td>
<td>***</td>
</tr>
<tr class="even">
<td>Time Foraging</td>
<td>2</td>
<td>20294</td>
<td>10147</td>
<td>65.37</td>
<td>&lt; 0.001</td>
<td>***</td>
</tr>
</tbody>
</table>
<p>Significance codes: *** p &lt; 0.001, ** p &lt; 0.01, * p &lt; 0.05</p>
<p><strong>Summary:</strong> Both bite rate and proportion of time foraging showed highly significant differences among species (p &lt; 0.001). The similar F values (69.95 and 65.37) indicate that species differences are equally strong for both feeding metrics.</p>
</section>
<section id="tukey-hsd-post-hoc-comparison-bite-rate-vs.-time-foraging" class="level2">
<h2 class="anchored" data-anchor-id="tukey-hsd-post-hoc-comparison-bite-rate-vs.-time-foraging">Tukey HSD Post-Hoc Comparison: Bite Rate vs.&nbsp;Time Foraging</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 13%">
<col style="width: 17%">
<col style="width: 21%">
<col style="width: 22%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Comparison</th>
<th>Bite Rate Diff</th>
<th>Bite Rate p-value</th>
<th>Time Foraging Diff</th>
<th>Time Foraging p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>C spilurus vs A triostegus</td>
<td>-19.51</td>
<td>&lt; 0.001 ***</td>
<td>-12.07</td>
<td>0.096</td>
</tr>
<tr class="even">
<td>Z cornutus vs A triostegus</td>
<td>-38.35</td>
<td>&lt; 0.001 ***</td>
<td>-60.21</td>
<td>&lt; 0.001 ***</td>
</tr>
<tr class="odd">
<td>Z cornutus vs C spilurus</td>
<td>-18.85</td>
<td>&lt; 0.001 ***</td>
<td>-48.14</td>
<td>&lt; 0.001 ***</td>
</tr>
</tbody>
</table>
<p>Significance codes: *** p &lt; 0.001, ** p &lt; 0.01, * p &lt; 0.05</p>
<p><strong>Summary:</strong> All species pairs differed significantly in bite rate (p &lt; 0.001). For time foraging, Z cornutus differed significantly from both A triostegus and C spilurus (p &lt; 0.001), but the difference between A triostegus and C spilurus was not statistically significant (p = 0.096). This suggests that while Manini and Parrotfish have different bite rates, they allocate a similar proportion of their time to foraging.</p>
</section>
</section>
<section id="t-test-1-a-triostegus" class="level1">
<h1>T-test 1: A triostegus</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="co"># T-test for A triostegus: Adults vs Juveniles</span></span>
<span id="cb91-2"><a href="#cb91-2" aria-hidden="true" tabindex="-1"></a><span class="co"># t.test() compares the two age classes</span></span>
<span id="cb91-3"><a href="#cb91-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb91-4"><a href="#cb91-4" aria-hidden="true" tabindex="-1"></a>t_test_atriostegus <span class="ot">&lt;-</span> Bites <span class="sc">%&gt;%</span></span>
<span id="cb91-5"><a href="#cb91-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Species <span class="sc">==</span> <span class="st">"A triostegus"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb91-6"><a href="#cb91-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">t.test</span>(Bites_per_min <span class="sc">~</span> Age_Class, <span class="at">data =</span> .) <span class="co"># data = . means "use the data that was piped in" </span></span>
<span id="cb91-7"><a href="#cb91-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb91-8"><a href="#cb91-8" aria-hidden="true" tabindex="-1"></a><span class="co"># View result</span></span>
<span id="cb91-9"><a href="#cb91-9" aria-hidden="true" tabindex="-1"></a>t_test_atriostegus <span class="co"># results are significant </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  Bites_per_min by Age_Class
t = -2.4046, df = 29.882, p-value = 0.02259
alternative hypothesis: true difference in means between group Adult and group Juvenile is not equal to 0
95 percent confidence interval:
 -29.652846  -2.413821
sample estimates:
   mean in group Adult mean in group Juvenile 
              31.86667               47.90000 </code></pre>
</div>
</div>
</section>
<section id="t-test-2-c-spilurus" class="level1">
<h1>T-test 2: C spilurus</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="co"># T-test for C spilurus: Adults vs Juveniles</span></span>
<span id="cb93-2"><a href="#cb93-2" aria-hidden="true" tabindex="-1"></a>t_test_cspil <span class="ot">&lt;-</span> Bites <span class="sc">%&gt;%</span></span>
<span id="cb93-3"><a href="#cb93-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Species <span class="sc">==</span> <span class="st">"C spilurus"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb93-4"><a href="#cb93-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">t.test</span>(Bites_per_min <span class="sc">~</span> Age_Class, <span class="at">data =</span> .)</span>
<span id="cb93-5"><a href="#cb93-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb93-6"><a href="#cb93-6" aria-hidden="true" tabindex="-1"></a><span class="co"># View result</span></span>
<span id="cb93-7"><a href="#cb93-7" aria-hidden="true" tabindex="-1"></a>t_test_cspil <span class="co"># results are significant </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  Bites_per_min by Age_Class
t = -3.9571, df = 36.1, p-value = 0.0003405
alternative hypothesis: true difference in means between group Adult and group Juvenile is not equal to 0
95 percent confidence interval:
 -18.225326  -5.874674
sample estimates:
   mean in group Adult mean in group Juvenile 
                 14.35                  26.40 </code></pre>
</div>
</div>
</section>
<section id="t-test-3-z-cornutus" class="level1">
<h1>T-test 3: Z cornutus</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a><span class="co"># T-test for Z cornutus: Adults vs Juveniles</span></span>
<span id="cb95-2"><a href="#cb95-2" aria-hidden="true" tabindex="-1"></a>t_test_zcor<span class="ot">&lt;-</span> Bites <span class="sc">%&gt;%</span></span>
<span id="cb95-3"><a href="#cb95-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Species <span class="sc">==</span> <span class="st">"Z cornutus"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb95-4"><a href="#cb95-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">t.test</span>(Bites_per_min <span class="sc">~</span> Age_Class, <span class="at">data =</span> .)</span>
<span id="cb95-5"><a href="#cb95-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb95-6"><a href="#cb95-6" aria-hidden="true" tabindex="-1"></a><span class="co"># View result</span></span>
<span id="cb95-7"><a href="#cb95-7" aria-hidden="true" tabindex="-1"></a>t_test_zcor <span class="co"># results are significant</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  Bites_per_min by Age_Class
t = -3.3215, df = 23.835, p-value = 0.002876
alternative hypothesis: true difference in means between group Adult and group Juvenile is not equal to 0
95 percent confidence interval:
 -3.1505440 -0.7351703
sample estimates:
   mean in group Adult mean in group Juvenile 
             0.5571429              2.5000000 </code></pre>
</div>
</div>
<section id="independent-t-test-results-adults-vs.-juveniles-by-species-bite-rate" class="level2">
<h2 class="anchored" data-anchor-id="independent-t-test-results-adults-vs.-juveniles-by-species-bite-rate">Independent T-Test Results: Adults vs.&nbsp;Juveniles by Species (Bite Rate)</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 9%">
<col style="width: 24%">
<col style="width: 27%">
<col style="width: 9%">
<col style="width: 5%">
<col style="width: 9%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>Species</th>
<th>Adult Mean (bites/min)</th>
<th>Juvenile Mean (bites/min)</th>
<th>t-value</th>
<th>df</th>
<th>p-value</th>
<th>Significant?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>A triostegus</td>
<td>31.87</td>
<td>47.90</td>
<td>-2.40</td>
<td>29.9</td>
<td>0.023</td>
<td>*</td>
</tr>
<tr class="even">
<td>C spilurus</td>
<td>14.35</td>
<td>26.40</td>
<td>-3.96</td>
<td>36.1</td>
<td>&lt; 0.001</td>
<td>***</td>
</tr>
<tr class="odd">
<td>Z cornutus</td>
<td>0.56</td>
<td>2.50</td>
<td>-3.32</td>
<td>23.8</td>
<td>0.003</td>
<td>**</td>
</tr>
</tbody>
</table>
<p>Significance codes: *** p &lt; 0.001, ** p &lt; 0.01, * p &lt; 0.05</p>
<p><strong>Summary:</strong> Juveniles had significantly higher bite rates than adults in all three species. This pattern was strongest in C spilurus (p &lt; 0.001) and weakest in A triostegus (p = 0.023) (due to high SD). Juvenile fish may feed more frequently due to higher metabolic demands associated with growth.</p>
</section>
</section>
<section id="plot--time-foraging-by-species" class="level1">
<h1>Plot- Time Foraging by Species</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Box plot of proportion of time feeding by species</span></span>
<span id="cb97-2"><a href="#cb97-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Box plot show the median, quartiles, and spread of data</span></span>
<span id="cb97-3"><a href="#cb97-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb97-4"><a href="#cb97-4" aria-hidden="true" tabindex="-1"></a>time_forage_plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> Time_Foraging_clean, </span>
<span id="cb97-5"><a href="#cb97-5" aria-hidden="true" tabindex="-1"></a>                            <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Species, </span>
<span id="cb97-6"><a href="#cb97-6" aria-hidden="true" tabindex="-1"></a>                                          <span class="at">y =</span> Prop_Time_Feeding, </span>
<span id="cb97-7"><a href="#cb97-7" aria-hidden="true" tabindex="-1"></a>                                          <span class="at">fill =</span> Species)) <span class="sc">+</span></span>
<span id="cb97-8"><a href="#cb97-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb97-9"><a href="#cb97-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">position =</span> <span class="fu">position_jitter</span>(<span class="at">width =</span> <span class="fl">0.1</span>), <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span> <span class="co"># add individual data points on top of boxes and spread out </span></span>
<span id="cb97-10"><a href="#cb97-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_d</span>(<span class="at">option =</span> <span class="st">"plasma"</span>) <span class="sc">+</span>  <span class="co"># Colorblind-friendly palette</span></span>
<span id="cb97-11"><a href="#cb97-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(  <span class="co"># Add labels</span></span>
<span id="cb97-12"><a href="#cb97-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Juvenile Foraging Time Allocation </span><span class="sc">\n</span><span class="st">Across Three Reef Fish Species"</span>,</span>
<span id="cb97-13"><a href="#cb97-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Proportion of observation period spent actively feeding"</span>,</span>
<span id="cb97-14"><a href="#cb97-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Species"</span>,</span>
<span id="cb97-15"><a href="#cb97-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Proportion of Time Feeding (%)"</span>) <span class="sc">+</span></span>
<span id="cb97-16"><a href="#cb97-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb97-17"><a href="#cb97-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>, <span class="co"># remove legend since species is already on x-axis</span></span>
<span id="cb97-18"><a href="#cb97-18" aria-hidden="true" tabindex="-1"></a>        <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">"bold"</span>, <span class="at">size =</span> <span class="dv">14</span>), <span class="co"># center titles</span></span>
<span id="cb97-19"><a href="#cb97-19" aria-hidden="true" tabindex="-1"></a>        <span class="at">plot.subtitle =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">size =</span> <span class="dv">11</span>, <span class="at">color =</span> <span class="st">"gray20"</span>),</span>
<span id="cb97-20"><a href="#cb97-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>), <span class="co"># make title larger</span></span>
<span id="cb97-21"><a href="#cb97-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"italic"</span>, <span class="at">size =</span> <span class="dv">10</span>)) <span class="co"># italicize sp name </span></span>
<span id="cb97-22"><a href="#cb97-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb97-23"><a href="#cb97-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the plot</span></span>
<span id="cb97-24"><a href="#cb97-24" aria-hidden="true" tabindex="-1"></a>time_forage_plot</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Plots_For_class_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="plot---bite-rate" class="level1">
<h1>Plot - Bite Rate</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter bite rate data to juveniles only</span></span>
<span id="cb98-2"><a href="#cb98-2" aria-hidden="true" tabindex="-1"></a>Bites_juveniles <span class="ot">&lt;-</span> Bites <span class="sc">%&gt;%</span></span>
<span id="cb98-3"><a href="#cb98-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Age_Class <span class="sc">==</span> <span class="st">"Juvenile"</span>)</span>
<span id="cb98-4"><a href="#cb98-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb98-5"><a href="#cb98-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Box plot of bite rate by species (juveniles only)</span></span>
<span id="cb98-6"><a href="#cb98-6" aria-hidden="true" tabindex="-1"></a>bite_rate_plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> Bites_juveniles, </span>
<span id="cb98-7"><a href="#cb98-7" aria-hidden="true" tabindex="-1"></a>                          <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Species, </span>
<span id="cb98-8"><a href="#cb98-8" aria-hidden="true" tabindex="-1"></a>                                        <span class="at">y =</span> Bites_per_min, </span>
<span id="cb98-9"><a href="#cb98-9" aria-hidden="true" tabindex="-1"></a>                                        <span class="at">fill =</span> Species)) <span class="sc">+</span></span>
<span id="cb98-10"><a href="#cb98-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb98-11"><a href="#cb98-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">position =</span> <span class="fu">position_jitter</span>(<span class="at">width =</span> <span class="fl">0.1</span>), <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb98-12"><a href="#cb98-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_d</span>(<span class="at">option =</span> <span class="st">"viridis"</span>) <span class="sc">+</span></span>
<span id="cb98-13"><a href="#cb98-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb98-14"><a href="#cb98-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Bite Rate"</span>,</span>
<span id="cb98-15"><a href="#cb98-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Species"</span>,</span>
<span id="cb98-16"><a href="#cb98-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Bites per Minute"</span>) <span class="sc">+</span></span>
<span id="cb98-17"><a href="#cb98-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb98-18"><a href="#cb98-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb98-19"><a href="#cb98-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.position =</span> <span class="st">"none"</span>,</span>
<span id="cb98-20"><a href="#cb98-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">"bold"</span>, <span class="at">size =</span> <span class="dv">14</span>),</span>
<span id="cb98-21"><a href="#cb98-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>),</span>
<span id="cb98-22"><a href="#cb98-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"italic"</span>, <span class="at">size =</span> <span class="dv">10</span>))</span>
<span id="cb98-23"><a href="#cb98-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb98-24"><a href="#cb98-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Display plot</span></span>
<span id="cb98-25"><a href="#cb98-25" aria-hidden="true" tabindex="-1"></a>bite_rate_plot</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Plots_For_class_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="plot---combine-bite-rate-foraging" class="level1">
<h1>Plot - Combine Bite Rate &amp; Foraging</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb99"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Combine the two plots side by side</span></span>
<span id="cb99-2"><a href="#cb99-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb99-3"><a href="#cb99-3" aria-hidden="true" tabindex="-1"></a>combined_plot <span class="ot">&lt;-</span> bite_rate_plot <span class="sc">+</span> time_forage_plot <span class="sc">+</span></span>
<span id="cb99-4"><a href="#cb99-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot_annotation</span>( <span class="co"># Add title for combined figure</span></span>
<span id="cb99-5"><a href="#cb99-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Comparison of Feeding Metrics Across Three Reef Fish Species"</span>,</span>
<span id="cb99-6"><a href="#cb99-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">theme =</span> <span class="fu">theme</span>(</span>
<span id="cb99-7"><a href="#cb99-7" aria-hidden="true" tabindex="-1"></a>      <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">"bold"</span>, <span class="at">size =</span> <span class="dv">16</span>)))</span>
<span id="cb99-8"><a href="#cb99-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb99-9"><a href="#cb99-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the combined plot</span></span>
<span id="cb99-10"><a href="#cb99-10" aria-hidden="true" tabindex="-1"></a>combined_plot</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Plots_For_class_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="plot---interaction-plot" class="level1">
<h1>Plot - Interaction Plot</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb100"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Interaction plot</span></span>
<span id="cb100-2"><a href="#cb100-2" aria-hidden="true" tabindex="-1"></a><span class="co"># plot 2-way anova and t-test results: species differences and adult vs juvenile differences </span></span>
<span id="cb100-3"><a href="#cb100-3" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate means and standard errors for each group</span></span>
<span id="cb100-4"><a href="#cb100-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb100-5"><a href="#cb100-5" aria-hidden="true" tabindex="-1"></a>interaction_data <span class="ot">&lt;-</span> Bites <span class="sc">%&gt;%</span></span>
<span id="cb100-6"><a href="#cb100-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Species, Age_Class) <span class="sc">%&gt;%</span>  <span class="co"># Group by species and age class</span></span>
<span id="cb100-7"><a href="#cb100-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>( <span class="co"># Calculate mean, standard deviation, sample size, and standard error</span></span>
<span id="cb100-8"><a href="#cb100-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_bites =</span> <span class="fu">mean</span>(Bites_per_min),</span>
<span id="cb100-9"><a href="#cb100-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">sd_bites =</span> <span class="fu">sd</span>(Bites_per_min),</span>
<span id="cb100-10"><a href="#cb100-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb100-11"><a href="#cb100-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">se_bites =</span> sd_bites <span class="sc">/</span> <span class="fu">sqrt</span>(n)) <span class="co"># Standard error = standard deviation divided by square root of n</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'Species'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb102"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Look at data</span></span>
<span id="cb102-2"><a href="#cb102-2" aria-hidden="true" tabindex="-1"></a>interaction_data</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 6
# Groups:   Species [3]
  Species      Age_Class mean_bites sd_bites     n se_bites
  &lt;chr&gt;        &lt;chr&gt;          &lt;dbl&gt;    &lt;dbl&gt; &lt;int&gt;    &lt;dbl&gt;
1 A triostegus Adult         31.9     26.0      20    5.82 
2 A triostegus Juvenile      47.9     14.6      20    3.26 
3 C spilurus   Adult         14.4      8.45     20    1.89 
4 C spilurus   Juvenile      26.4     10.7      20    2.39 
5 Z cornutus   Adult          0.557    0.885    20    0.198
6 Z cornutus   Juvenile       2.5      2.46     20    0.550</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb104"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb104-1"><a href="#cb104-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Interaction plot</span></span>
<span id="cb104-2"><a href="#cb104-2" aria-hidden="true" tabindex="-1"></a>interaction_plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> interaction_data, </span>
<span id="cb104-3"><a href="#cb104-3" aria-hidden="true" tabindex="-1"></a>                            <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Age_Class, </span>
<span id="cb104-4"><a href="#cb104-4" aria-hidden="true" tabindex="-1"></a>                                          <span class="at">y =</span> mean_bites, </span>
<span id="cb104-5"><a href="#cb104-5" aria-hidden="true" tabindex="-1"></a>                                          <span class="at">color =</span> Species,</span>
<span id="cb104-6"><a href="#cb104-6" aria-hidden="true" tabindex="-1"></a>                                          <span class="at">group =</span> Species)) <span class="sc">+</span></span>
<span id="cb104-7"><a href="#cb104-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span> <span class="co"># add lines connecting adult to juvenile for each species</span></span>
<span id="cb104-8"><a href="#cb104-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span>  <span class="co"># Add points for each mean</span></span>
<span id="cb104-9"><a href="#cb104-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> mean_bites <span class="sc">-</span> se_bites, <span class="co"># Add error bars (mean ± standard error)</span></span>
<span id="cb104-10"><a href="#cb104-10" aria-hidden="true" tabindex="-1"></a>                    <span class="at">ymax =</span> mean_bites <span class="sc">+</span> se_bites),</span>
<span id="cb104-11"><a href="#cb104-11" aria-hidden="true" tabindex="-1"></a>                <span class="at">width =</span> <span class="fl">0.1</span>) <span class="sc">+</span></span>
<span id="cb104-12"><a href="#cb104-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_viridis_d</span>(<span class="at">option =</span> <span class="st">"viridis"</span>) <span class="sc">+</span> <span class="co"># Colorblind-friendly palette</span></span>
<span id="cb104-13"><a href="#cb104-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>( <span class="co"># labels</span></span>
<span id="cb104-14"><a href="#cb104-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Interaction Between Species and Age Class on Bite Rate"</span>,</span>
<span id="cb104-15"><a href="#cb104-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Lines show change from adult to juvenile within each species"</span>,</span>
<span id="cb104-16"><a href="#cb104-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Age Class"</span>,</span>
<span id="cb104-17"><a href="#cb104-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Mean Bites per Minute (± SE)"</span>,</span>
<span id="cb104-18"><a href="#cb104-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"Species"</span>) <span class="sc">+</span></span>
<span id="cb104-19"><a href="#cb104-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb104-20"><a href="#cb104-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb104-21"><a href="#cb104-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">"bold"</span>, <span class="at">size =</span> <span class="dv">14</span>),</span>
<span id="cb104-22"><a href="#cb104-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.subtitle =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">size =</span> <span class="dv">11</span>, <span class="at">color =</span> <span class="st">"gray40"</span>),</span>
<span id="cb104-23"><a href="#cb104-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>),</span>
<span id="cb104-24"><a href="#cb104-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.text =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"italic"</span>))</span>
<span id="cb104-25"><a href="#cb104-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb104-26"><a href="#cb104-26" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the plot</span></span>
<span id="cb104-27"><a href="#cb104-27" aria-hidden="true" tabindex="-1"></a>interaction_plot</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Plots_For_class_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>